name: Dispatch Metadata

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Parse Version
        id: semver
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version#v}"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Load Config Metadata
        id: config
        run: |
          # You could also `cat config.json` or read from a YAML and convert
          config=`cat config.json`
          echo "config=$config" >> $GITHUB_OUTPUT

      - name: Send Dispatch Event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.METADATA_REPO_PAT }}" \
            https://api.github.com/repos/TRAINFACED/trainfaced/dispatches \
            -d '{
              "event_type": "new-release",
              "client_payload": {
                "sender": "${{ github.repository }}",
                "version": "${{ steps.semver.outputs.version }}",
                "config": ${{ steps.config.outputs.config }}
              }
            }'
# on:
#   workflow_call:
#     inputs:
#       config_json:
#         required: true
#         type: string
#       token_secret_name:
#         required: false
#         type: string
#     secrets:
#       METADATA_REPO_PAT:
#         required: true